version: '3.9'

services:
  redis-db:
    image: 'redis:alpine'
    container_name: redis-db
    command: redis-server
    env_file:
      - ../../common.env
      - ../../envs/${CHAIN_ENV_FILE}
    volumes:
      - ../${SCAN_DATA_DIR-.}/redis-data:/data
