services:
  init:
    build:
      context: .
    pull_policy: always
    image: dreamcacao/builderism_scan:latest
    command: [ "/bin/bash", "/script/init-entrypoint.sh" ]
    volumes:
      - ${CONFIG_DIR}:/config
      - ${SCAN_DATA_DIR}:/data
      - ./init-entrypoint.sh:/script/init-entrypoint.sh
    env_file:
      - ../common.env
      - ../envs/${CHAIN_ENV_FILE}
  indexer:
    image: dreamcacao/builderism_scan:latest
    pull_policy: always
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - ${SCAN_DATA_DIR}:/data
      - ./indexer-entrypoint.sh:/script/indexer-entrypoint.sh
    command: [ "/bin/bash", "/script/indexer-entrypoint.sh" ]
    env_file:
      - ../common.env
      - ../envs/${CHAIN_ENV_FILE}
  explorer:
    image: dreamcacao/builderism_scan:latest
    pull_policy: always
    depends_on:
      - indexer
    ports:
      - 3000:3000
    volumes:
      - ${SCAN_DATA_DIR}:/data
      - ./explorer-entrypoint.sh:/script/explorer-entrypoint.sh
    command: [ "/bin/bash", "/script/explorer-entrypoint.sh" ]
    env_file:
      - ../common.env
      - ../envs/${CHAIN_ENV_FILE}
