services:
  init:
    build:
      context: .
    image: dreamcacao/builderism_run:latest
    pull_policy: always
    command: [ "bash", "/script/init-entrypoint.sh" ]
    volumes:
      - ${GETH_DATA_DIR}:/data
      - ${CONFIG_DIR}:/config
      - ./init-entrypoint.sh:/script/init-entrypoint.sh
      - ./snapshot:/snapshot
    env_file:
      - ../common.env
      - ../envs/${CHAIN_ENV_FILE}
  geth:
    image: dreamcacao/builderism_run:latest
    pull_policy: always
    depends_on:
      init:
        condition: service_completed_successfully
    command: [ "bash", "/script/geth-entrypoint.sh" ]
    ports:
      - 8545:8545 # http
      - 8546:8546 # ws
      - 8551:8551 # auth http
    volumes:
      - ${GETH_DATA_DIR}:/data
      - ${CONFIG_DIR}:/config
      - ./geth-entrypoint.sh:/script/geth-entrypoint.sh
    networks:
      - op-network
    env_file:
      - ../common.env
      - ../envs/${CHAIN_ENV_FILE}
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "7"
  node:
    image: dreamcacao/builderism_run:latest
    pull_policy: always
    depends_on:
      - geth
    command: [ "bash", "/script/op-node-entrypoint.sh" ]
    networks:
      - op-network
    volumes:
      - ${GETH_DATA_DIR}:/data
      - ${CONFIG_DIR}:/config
      - ./op-node-entrypoint.sh:/script/op-node-entrypoint.sh
    ports:
      - 8547:8547 # RPC
      - 9222:9222
      - 9222:9222/udp
    env_file:
      - ../common.env
      - ../envs/${CHAIN_ENV_FILE}
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "7"
  batcher:
    image: dreamcacao/builderism_run:latest
    pull_policy: always
    depends_on:
      - node
    command: [ "bash", "/script/op-batcher-entrypoint.sh" ]
    volumes:
      - ${CONFIG_DIR}:/config
      - ./op-batcher-entrypoint.sh:/script/op-batcher-entrypoint.sh
    networks:
      - op-network
    env_file:
      - ../common.env
      - ../envs/${CHAIN_ENV_FILE}
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "7"
  proposer:
    image: dreamcacao/builderism_run:latest
    pull_policy: always
    depends_on:
      - batcher
    command: [ "bash", "/script/op-proposer-entrypoint.sh" ]
    volumes:
      - ${CONFIG_DIR}:/config
      - ./op-proposer-entrypoint.sh:/script/op-proposer-entrypoint.sh
    networks:
      - op-network
    env_file:
      - ../common.env
      - ../envs/${CHAIN_ENV_FILE}
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "7"
networks:
  op-network:
    driver: bridge
